### ISSUE TITLE
Saving the loaded campaign

### ISSUE THREAD

**Issue by Antafes** [cniemira/maptool-StandaloneServer#4]
Do you think it is possible to save the currently loaded campaign directly on the server?
I haven't looked over this part of the maptools code so far.

**Comment by cniemira** [comment]
Anything's possible, but it might not be worth the effort.

The first problem is that there would have to be a way to interact with the server and send it instructions. The copout there would be to add a signal handler and a wrapper script. Something like a SIGUSR to the JVM could instruct the process to save the current campaign. But signal handlers are a fairly blunt tool, although, a graceful shutdown on SIGQUIT wouldn't hurt. Still, the better option, IMHO, would be to implement a control thread in the server and interact with it via some RPC. I'd thought of leveraging the chat system for that... say if the GM did something like '/w server save' for example. But then there has to be an RPC handler, and that's a whole lot of new code, and it's still very much a big hammer approach.

Now, I'm not saying it's not worth while... but I think right way to talk to the server is via the client and not an some additional interface. That said, I also think that MT needs a lot of work in general, and I'd hate to see us going down one path when the project goes in a different direction. I started on a project a few months ago to segregate the client and server code a bit more. Personally, I'd like to see them as completely atomic entities communicating via a well-defined protocol. I'm not sure if that's where the official roadmap goes, but I think it makes sense, because it opens up the door for a lot of possibilities. Right now the RPC is all Hessian, but with a little work, I think it would be possible to add an HTTP REST API. With a more flexible communication mechanism between client and server, it would be just as easy to signal the server to save a file as it would to build a new standalone HTML5 client.

Okay, maybe not just as easy, but...

**Comment by Antafes** [comment]
That sounds very nice and I'm waiting to see the results :)

**Comment by cniemira** [comment]
I've added some very basic support for a save-on-quit function. It's in the branch labeled `issue-4` and is activated with the `-o` flag. At shutdown (say, `^c`-ing a running JVM), the active campaign will be saved. Consider it experimental (back up your cmpgn files!) for now. :-)
